### ISSUE TITLE
Crash: CaptureSDK block_destroy_helper

### ISSUE THREAD

**Issue by ghost** [SocketMobile/cocoapods-capturesdk#2] opened 2022-10-03 18:58 UTC
Hi,

Please see stack trace for crash experienced using CaptureSDK 1.4.51. Can this be addressed in an upcoming release?

Crashed: NSOperationQueue 0x14bdcf050 (QOS: UNSPECIFIED)
0  CaptureSDK                     0x6b610 block_destroy_helper + 18548
1  CaptureSDK                     0x6a208 block_destroy_helper + 13420
2  CaptureSDK                     0x6817c block_destroy_helper + 5088
3  CaptureSDK                     0x111d4 -[SKTCapture didReceiveEvent:withHandle:withResult:] + 196
4  CaptureSDK                     0x31d98 -[SKTCaptureServiceDirect consumeFromCaptureHandle:] + 808
5  CaptureSDK                     0x32198 __72-[SKTCaptureServiceDirect doConsumeFromCaptureHandle:completionHandler:]_block_invoke + 36
6  Foundation                     0x51c1c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
7  Foundation                     0x63f94 -[NSBlockOperation main] + 104
8  Foundation                     0x3c214 __NSOPERATION_IS_INVOKING_MAIN__ + 24
9  Foundation                     0x4d5dc -[NSOperation start] + 788
10 Foundation                     0x50c68 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
11 Foundation                     0x5ee10 __NSOQSchedule_f + 184
12 libdispatch.dylib              0x12830 _dispatch_block_async_invoke2 + 148
13 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
14 libdispatch.dylib              0x6eec _dispatch_continuation_pop + 500
15 libdispatch.dylib              0x6558 _dispatch_async_redirect_invoke + 584
16 libdispatch.dylib              0x15164 _dispatch_root_queue_drain + 396
17 libdispatch.dylib              0x1596c _dispatch_worker_thread2 + 164
18 libsystem_pthread.dylib        0x1080 _pthread_wqthread + 228
19 libsystem_pthread.dylib        0xe5c start_wqthread + 8

**Comment by cyrille-socket** [comment] 2022-10-03 19:05
Hi @michael-ps,

can you try the latest version please? The 1.5.7: https://github.com/SocketMobile/cocoapods-capturesdk/releases/tag/1.5.7

**Comment by ghost** [comment] 2022-10-03 19:09
Hi @cyrille-socket,

Thanks for your response. Was there a fix applied for this issue since version 1.4.51? Updating the SDK is expensive for us as it requires a full regression testing cycle.

**Comment by cyrille-socket** [comment] 2022-10-04 08:58
Hi @michael-ps,

following your stack trace it's a bit difficult to say what is the cause of the crash. I understand that you have some tests to run again but it's the only way to know. We constantly improve our SDK with small bug fixes and improvements so it might be fixe in the next versions following yours.

Also, can you provide the code where you use the SDK with the commands that you send to the device? Which device you use? Which iOS version?

Thank you

**Comment by tanklin** [comment] 2023-04-11 12:28
Hi @cyrille-socket,

I got the same stack trace here, and we're using the s700 device with the SDK version `1.5.9` in the app, which happened from iOS 15 to 16.

Would you please check if the following stacks I provided will be fixed on the latest version?

Thank you.

```
Crashed: NSOperationQueue 0x108493ff0 (QOS: UNSPECIFIED)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

Crashed: NSOperationQueue 0x108493ff0 (QOS: UNSPECIFIED)
0  CaptureSDK                     0x69360 block_destroy_helper + 18360
1  CaptureSDK                     0x65f94 block_destroy_helper + 5100
2  CaptureSDK                     0xd440 -[SKTCapture didReceiveEvent:withHandle:withResult:] + 180
3  CaptureSDK                     0x2e398 -[SKTCaptureServiceDirect consumeFromCaptureHandle:] + 780
4  CaptureSDK                     0x2e75c __72-[SKTCaptureServiceDirect doConsumeFromCaptureHandle:completionHandler:]_block_invoke + 36
5  Foundation                     0x50a9c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
6  Foundation                     0x62e14 -[NSBlockOperation main] + 104
7  Foundation                     0x3b1c4 __NSOPERATION_IS_INVOKING_MAIN__ + 24
8  Foundation                     0x4c4e0 -[NSOperation start] + 788
9  Foundation                     0x4fae8 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
10 Foundation                     0x5dc90 __NSOQSchedule_f + 184
11 libdispatch.dylib              0x12830 _dispatch_block_async_invoke2 + 148
12 libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
13 libdispatch.dylib              0x6eec _dispatch_continuation_pop + 500
14 libdispatch.dylib              0x6558 _dispatch_async_redirect_invoke + 588
15 libdispatch.dylib              0x15164 _dispatch_root_queue_drain + 396
16 libdispatch.dylib              0x1596c _dispatch_worker_thread2 + 164
17 libsystem_pthread.dylib        0x1080 _pthread_wqthread + 228
18 libsystem_pthread.dylib        0xe5c start_wqthread + 8
```

**Comment by cyrille-socket** [comment] 2024-07-15 13:30
No more activity on this thread since more than 1 year.

**Closed as completed by cyrille-socket** 2024-07-15 13:30 UTC
