### ISSUE TITLE
Crash: CaptureSDK  CSktXmlTag::~CSktXmlTag()

### ISSUE THREAD

**Issue by ChernyshenkoTaras** [SocketMobile/cocoapods-capturesdk#9] opened 2023-10-26 13:41 UTC
Hi,
I encountered a crash while using the iOS application, and it appears to be related to the CaptureSDK 1.6. I would greatly appreciate your assistance in resolving this issue. Please let me know if you require any additional information.

iOS version: 14.6
Device: iPhone 7
SDK: CaptureSDK 1.6

Stack trace:
```
Crashed: Thread #1
SIGABRT ABORT 0x00000001d20817b0

Crashed: Thread
0  libsystem_kernel.dylib         0x277b0 __pthread_kill + 8
1  libsystem_pthread.dylib        0xa9c0 pthread_kill + 212
2  libsystem_c.dylib              0x73a44 abort + 100
3  libsystem_malloc.dylib         0x1d0a8 _malloc_put + 554
4  libsystem_malloc.dylib         0x1d260 malloc_report + 60
5  libsystem_malloc.dylib         0x13448 free + 444
6  CaptureSDK                     0x81bbc CSktXmlTag::~CSktXmlTag() + 52
7  CaptureSDK                     0x81c8c CSktXmlTag::~CSktXmlTag() + 20
8  CaptureSDK                     0x82b5c CSktXmlParser::Parse(char const*, unsigned long) + 88
9  CaptureSDK                     0x6f6b8 CSktConfigXml::Load(char const*, char const*, char const*) + 488
10 CaptureSDK                     0x676e8 CSktCaptureConfiguration::RetrieveConfiguration(CSktConfigXml*) + 108
11 CaptureSDK                     0x64960 CSktCaptureConfiguration::ReadSerialPorts(char*, unsigned int) + 96
12 CaptureSDK                     0x68f9c CSktCapture::ReadConfiguration(char const*, TSktCaptureObject**) + 336
13 CaptureSDK                     0x13efc SktCaptureListenerThread(void*) + 296
14 libsystem_pthread.dylib        0x9c74 _pthread_start + 288
15 libsystem_pthread.dylib        0xe878 thread_start + 8
```

**Comment by cyrille-socket** [comment] 2023-10-26 16:11
Hi @ChernyshenkoTaras

please update to the latest CaptureSDK version 1.8.34. We have fixe this crash.

Also please use https://github.com/SocketMobile/swift-package-capturesdk. We will deprecate the Cocoapods in a year or so.

**Comment by ChernyshenkoTaras** [comment] 2023-11-08 12:56
Hi there,

The same issue is still reproduces with the CaptureSDK version 1.8.34. This time it happened on iOS 15.8.0 and iPhone 7 Plus

**Comment by cyrille-socket** [comment] 2023-12-06 20:54
Hi @ChernyshenkoTaras 

would you be able to send us the XML file that our CaptureSDK creates in your app?

Do you reproduce when running your app on a device by yourself or is it only from crashes from some of your customers?

Do you set a config with a `setProperty` and the property ID `SKTCapturePropertyIDConfiguration` in your code to do something in particular?

Thank you for your answers

Cyrille

**Comment by Pranit-Harekar** [comment] 2023-12-11 17:10
Hi @cyrille-socket - may I know the reason behind deprecating the Cocoapods library and instead switching to SPM?

**Comment by ios-dev-socket** [comment] 2023-12-12 13:00
Hi @Pranit-Harekar,

since some time now, publishing with Cocoapods slows our release process down. Now SPM is the new sheriff in town and a lot of developers have migrated and really simplifies the integration of external dependencies in Xcode project without having additional code or script that sometimes fail, it's really a game changer.

Also an Xcode project can have both SPM and Cocoapods dependencies. So developers who don't want to remove all their Cocoapods can at least use SPM for our SDK in the future.

We will deprecate our Cocoapods in 1 year (1/1/2025).

**Comment by cyrille-socket** [comment] 2023-12-21 14:49
Hi @ChernyshenkoTaras ,

can you send us your xml file please?

**Comment by ChernyshenkoTaras** [comment] 2023-12-21 15:02
Hi @cyrille-socket ! 
Could u explain please where I can locate this xml file? I'm still using cocoapods in my project for installation of CaptureSDK if that's matter

**Comment by cyrille-socket** [comment] 2023-12-22 13:16
It's in the following folder of the app: Library/Caches/Capture.xml

<img width="745" alt="capture xml socket" src="https://github.com/SocketMobile/cocoapods-capturesdk/assets/92016576/bb1c6f89-ea91-45e5-b1a8-c7548c60f716">

**Comment by cyrille-socket** [comment] 2024-01-08 10:15
Hi @ChernyshenkoTaras . Any update on this?

**Comment by ChernyshenkoTaras** [comment] 2024-01-12 15:12
Hi @cyrille-socket Sorry for long response, here is the xml file

```
<Capture>
<Config>
<SerialPorts Value="com.socketmobile.chs"/>
<DataConfirmationMode Value="0"/>
<DataConfirmationAction Value="5"/>
<SocketCam Value="enabled"/>
<Version Value="1.8"/>
<License Value="licenseFondue"/>
<ExpireDate Value=""/>
</Config>
<SocketCam>
<5>
<FriendlyName Value="SocketCam C820"/>
<DecodeAction Value="5"/>
<DataSources>
<Ean13 Value="1"/>
<Upce Value="1"/>
<Ean8 Value="1"/>
<QrCode Value="1"/>
<Code128 Value="1"/>
<Code39 Value="1"/>
<Code39 Value="1"/>
<Code93 Value="1"/>
<Pdf417 Value="1"/>
<Datamatrix Value="1"/>
<Interleaved Value="1"/>
<AZTEC Value="1"/>
</DataSources>
</5>
<29>
<Expires Value=""/>
<ProcessStarted Value=""/>
<FriendlyName Value="SocketCam C860"/>
<DecodeAction Value="5"/>
<DataSources>
<Upca Value="1"/>
<Upce Value="1"/>
<Ean8 Value="1"/>
<Ean13 Value="1"/>
<Code128 Value="1"/>
<Gs1 Value="1"/>
<C128 Value="1"/>
<Code39 Value="1"/>
<Trioptic Value="1"/>
<Interleaved Value="1"/>
<S25 Value="1"/>
<M25 Value="1"/>
<Code93 Value="1"/>
<Code11 Value="1"/>
<Codabar Value="1"/>
<Pdf417 Value="1"/>
<Micropdf Value="1"/>
<AZTEC Value="1"/>
<Maxicode Value="1"/>
<Datamatrix Value="1"/>
<QrCode Value="1"/>
<Telepen Value="1"/>
<Msi Value="1"/>
<Codablock Value="1"/>
<Composite Value="1"/>
<Hanxin Value="1"/>
<Hk25 Value="1"/>
<Koreapost Value="1"/>
</DataSources>
</29>
</SocketCam>
<DataEditing>
<CurrentProfile Value=""/>
</DataEditing>
<Ble>
<Favorites Value=""/>
</Ble>
</Capture>

```

**Comment by cyrille-socket** [comment] 2024-01-15 10:27
Hi @ChernyshenkoTaras,

I investigated with your file and I can't reproduce any crash. The format, the keys and the values are ok.

Do you reproduce on your end on development simulators or development devices at least?

**Comment by ChernyshenkoTaras** [comment] 2024-01-16 07:13
Hi @cyrille-socket,

The crash was reproduced only once on our side, and we were not able to reproduce it again. This seems to be a quite rare issue, as in the last 30 days only 35 people encountered it, according to Crashlytics. However, it appears that for most of them the crash occurred more than once, since we have recorded 51 crashes in the last 30 days.

I suspect the crash reproduces more often on older devices. Most crashes occurred on iPhone 6 and 7 models. Here are the details:
<img width="562" alt="capture-sdk-crash" src="https://github.com/SocketMobile/cocoapods-capturesdk/assets/9074648/feb509ed-eda9-4ab5-9be1-346be0820c18">

**Comment by cyrille-socket** [comment] 2024-03-20 14:44
This crash has been fixed in the new release `1.9.18` in our [Developer Portal](https://www.socketmobile.com/developers/portal)

**Closed as completed by cyrille-socket** 2024-03-20 14:44 UTC

**Comment by Pranit-Harekar** [comment] 2024-06-06 22:15
@cyrille-socket @ios-dev-socket Regarding the [previous comment](https://github.com/SocketMobile/cocoapods-capturesdk/issues/9#issuecomment-1851991747), it looks like the [SPM package](https://github.com/SocketMobile/swift-package-capturesdk) is also deprecated. Are you going to deprecate both Cocoapods and SPM? Please let me know, thanks!

**Comment by cyrille-socket** [comment] 2024-06-07 08:54
Hi @Pranit-Harekar. Yes we did deprecate Cocoapods and SPM on our Github page. They're now available through our [Developer Portal](https://www.socketmobile.com/developers/portal) for technical reasons.
